@startuml

class blocks.Invoice {
    ID
    client
    data wystawienia
    tax()
    totalValue()
}

class blocks.Client {
    Imię
    Nazwisko
    Adres
    PESEL
    validate()
}

class blocks.InvoiceElement{
    Nazwa
    Cena
    Stawaka VAT
    Ilość
    tax()
    totalValue()
}

class handlers.InvoiceHandler{
    ArrayList faktury
    createInvoice()
    showInvoice()
}

class handlers.ClientHandler{
    ArrayList klienci
    createClient()
    ? addClientToInvoice() ?
}

class adapters.Adapter {

}
class handlers.InvoiceElementHandler {

}

class GUI.MainFrame{

}

class GUI.NewInvoiceFrame {
    createInvoice()
}

class GUI.ShowInvoicesFrame {
    showInvoices()
}

GUI.NewInvoiceFrame -- adapters.Adapter
GUI.MainFrame -- GUI.ShowInvoicesFrame
GUI.MainFrame -- GUI.NewInvoiceFrame
GUI.ShowInvoicesFrame -- handlers.InvoiceHandler
adapters.Adapter -- handlers.ClientHandler
adapters.Adapter -- handlers.InvoiceHandler
adapters.Adapter -- handlers.InvoiceElementHandler
blocks.Invoice *- blocks.Client
blocks.Invoice o-- blocks.InvoiceElement
handlers.InvoiceHandler -- blocks.Invoice
handlers.ClientHandler --- blocks.Client
handlers.InvoiceElementHandler -- blocks.InvoiceElement

@enduml