@startuml

class blocks.Invoice {
    ID
    client
    data wystawienia
    tax()
    totalValue()
}

class blocks.Client {
    Imię
    Nazwisko
    Adres
    PESEL
    validate()
}

class blocks.InvoiceElement{
    Nazwa
    Cena
    Stawaka VAT
    Ilość
    tax()
    totalValue()
}

class handlers.InvoiceHandler{
    ArrayList faktury
    createInvoice()
    showInvoice()
}

class handlers.ClientHandler{
    ArrayList klienci
    createClient()
    ? addClientToInvoice() ?
}

class GUI {

}


GUI -- handlers.ClientHandler
GUI -- handlers.InvoiceHandler
blocks.Invoice *-- blocks.Client
blocks.Invoice o-- blocks.InvoiceElement
handlers.InvoiceHandler -- blocks.Invoice
handlers.InvoiceHandler - blocks.InvoiceElement
handlers.ClientHandler --- blocks.Client

@enduml