@startuml

class App
class Frame{
    Dialog
}
class MenuBar{
    parent
}
class Button{
    parent
    setDialogVisible(0
}
Class Dialog{
    text: "Hello World!"
}
class MenuItem{
    change color()
}

App - Frame
Frame o-- MenuBar
MenuBar o-- MenuItem
Frame o-- Button

Frame o-- Dialog



@enduml